# Generated by Django 3.1.2 on 2020-10-19 16:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_init', models.DateTimeField(editable=False)),
                ('timestamp_fin', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('samp_frequency', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('longi', models.CharField(max_length=255, null=True)),
                ('registered_by', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuring_dimentions', models.JSONField()),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.JSONField(editable=False)),
                ('time_start', models.DateTimeField(editable=False)),
                ('time_end', models.DateTimeField(editable=False)),
                ('captured_data', models.JSONField(editable=False)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.collect')),
            ],
        ),
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('devolution_date', models.DateTimeField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.equipment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.patient')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='sensors',
            field=models.ManyToManyField(to='endpoint.Sensor'),
        ),
        migrations.AddField(
            model_name='collect',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.equipment'),
        ),
        migrations.AddField(
            model_name='collect',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.patient'),
        ),
    ]
