# Generated by Django 3.1.2 on 2020-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_auto_20201019_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='time_end',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='time_start',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
