# Generated by Django 3.1.2 on 2020-10-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cpf',
            new_name='id',
        ),
    ]
