# Generated by Django 3.1.2 on 2020-10-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_auto_20201019_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collect',
            old_name='patient_id',
            new_name='patient',
        ),
    ]
